version: 0.0
os: linux
files:
  - source: /
    destination: /flaskapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  Application:
  - location: scripts/start_server.sh
    timeout: 300
    runas: root
